# Euler Project problem 12 by T. Ruzmetov 04/21/2017

# The sequence of triangle numbers is generated by adding the
# natural numbers. So the 7th triangle number would be
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1:  1
# 3:  1,3
# 6:  1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?


# this fnction counts number of divisors for a given number
divSum <- function(x) { 
            sq_x <- sqrt(x)
            sq_x_fl <- floor(sq_x)
            
            if (x <= 2) {
                    y <- x
            } else {
                    y <- 2*sum(x %% 2:(sq_x_fl + 1 ) == 0) + 2    
            }
            
            if((sq_x-sq_x_fl) == 0){
                y <- y - 1
            }
            y
} 


n <- 10000000

for (i in 1000:n) { 
    nth_tri <- i*(i+1)/2
    
    if(divSum(nth_tri) > 500) {
        break;
    }
}

nth_tri

# It took around 2 secx, which is not bad, but not very efficient for scaling!
# Most efficient approach would be finding finding devisors of triangular number
# by factoring degrees of primes.
# nth_tri = p1^a1 + p2^a2 + .....
# n_divs = (a1+1)*(a2+1)*.....