# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2,the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# brute force method
x <- 0
x[1] <- 1
x[2] <- 2
i <- 2
repeat{
    i <- i + 1
    x[i] <- x[i-1] + x[i-2]
    if(x[i] > 4e+06){
        break
    }
}

x <- x[x < 4000000]
sum(x[x%%2 == 0])
